// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBffd-8Ai__hKrVj1Kme6i1z0MEFjGUj_4',
    appId: '1:828612256891:web:b24833282ff8c1e2e5eede',
    messagingSenderId: '828612256891',
    projectId: 'inventorymanagement-221b2',
    authDomain: 'inventorymanagement-221b2.firebaseapp.com',
    storageBucket: 'inventorymanagement-221b2.firebasestorage.app',
    measurementId: 'G-LZW4QJ90SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxot4m4BXkX1Z_ICFknk8HFCXLDLihK-8',
    appId: '1:828612256891:android:5323c23f4f2362fbe5eede',
    messagingSenderId: '828612256891',
    projectId: 'inventorymanagement-221b2',
    storageBucket: 'inventorymanagement-221b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0JMS0U9U68_TTMTnnuQK5saeYtrpD63Q',
    appId: '1:828612256891:ios:0232f0ec5ea55a7fe5eede',
    messagingSenderId: '828612256891',
    projectId: 'inventorymanagement-221b2',
    storageBucket: 'inventorymanagement-221b2.firebasestorage.app',
    iosBundleId: 'com.example.theisiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0JMS0U9U68_TTMTnnuQK5saeYtrpD63Q',
    appId: '1:828612256891:ios:0232f0ec5ea55a7fe5eede',
    messagingSenderId: '828612256891',
    projectId: 'inventorymanagement-221b2',
    storageBucket: 'inventorymanagement-221b2.firebasestorage.app',
    iosBundleId: 'com.example.theisiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBffd-8Ai__hKrVj1Kme6i1z0MEFjGUj_4',
    appId: '1:828612256891:web:1c421c5400209870e5eede',
    messagingSenderId: '828612256891',
    projectId: 'inventorymanagement-221b2',
    authDomain: 'inventorymanagement-221b2.firebaseapp.com',
    storageBucket: 'inventorymanagement-221b2.firebasestorage.app',
    measurementId: 'G-PHFHXVBB6M',
  );
}
